# Generated by Django 5.2.7 on 2026-01-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'ARTICULOS',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('es_control', models.CharField(default='SI', max_length=5)),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controles',
                'db_table': 'CONTROLES',
            },
        ),
        migrations.CreateModel(
            name='PlanillaMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(blank=True, max_length=50, null=True)),
                ('num_op', models.IntegerField(blank=True, null=True, verbose_name='Número OP')),
                ('id_proceso', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('cantidad_realizada', models.FloatField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_elaborador', models.IntegerField(blank=True, null=True)),
                ('id_aprobador', models.IntegerField(blank=True, null=True)),
                ('fecha_elaborador', models.DateField(blank=True, null=True)),
                ('fecha_aprobador', models.DateField(blank=True, null=True)),
                ('id_elemento', models.IntegerField(blank=True, null=True)),
                ('articulo', models.ForeignKey(db_column='id_articulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.articulo')),
            ],
            options={
                'verbose_name': 'Planilla de Medición',
                'verbose_name_plural': 'Planillas de Medición',
                'db_table': 'PLANILLAMEDICION',
            },
        ),
        migrations.CreateModel(
            name='Tolerancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('posicion', models.IntegerField(default=0)),
                ('id_instrumento', models.IntegerField(blank=True, null=True)),
                ('control', models.ForeignKey(db_column='id_control', on_delete=django.db.models.deletion.CASCADE, to='mediciones.control')),
                ('planilla', models.ForeignKey(db_column='id_planilla', on_delete=django.db.models.deletion.CASCADE, to='mediciones.planillamedicion')),
            ],
            options={
                'verbose_name': 'Tolerancia',
                'verbose_name_plural': 'Tolerancias',
                'db_table': 'TOLERANCIAS',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='ValorMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.IntegerField()),
                ('valor_pieza', models.FloatField(blank=True, null=True)),
                ('valor_pnp', models.CharField(blank=True, max_length=5, null=True)),
                ('posicion', models.IntegerField(default=0)),
                ('id_operario', models.IntegerField(blank=True, null=True)),
                ('id_instrumento', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('op', models.CharField(blank=True, max_length=20, null=True)),
                ('control', models.ForeignKey(db_column='id_control', on_delete=django.db.models.deletion.CASCADE, to='mediciones.control')),
                ('planilla', models.ForeignKey(db_column='id_planilla', on_delete=django.db.models.deletion.CASCADE, to='mediciones.planillamedicion')),
                ('tolerancia', models.ForeignKey(blank=True, db_column='id_tolerancia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.tolerancia')),
            ],
            options={
                'verbose_name': 'Valor de Medición',
                'verbose_name_plural': 'Valores de Medición',
                'db_table': 'VALORMEDICION',
                'ordering': ['pieza', 'posicion'],
            },
        ),
    ]
