# Generated by Django 5.2.7 on 2026-01-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'db_table': 'ELEMENTOS',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'db_table': 'PROCESOS',
            },
        ),
        migrations.RemoveField(
            model_name='planillamedicion',
            name='id_elemento',
        ),
        migrations.RemoveField(
            model_name='planillamedicion',
            name='id_proceso',
        ),
        migrations.AddField(
            model_name='control',
            name='pnp',
            field=models.BooleanField(default=False, verbose_name='PnP'),
        ),
        migrations.AddField(
            model_name='planillamedicion',
            name='elemento',
            field=models.ForeignKey(db_column='id_elemento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.elemento'),
        ),
        migrations.AddField(
            model_name='planillamedicion',
            name='proceso',
            field=models.ForeignKey(db_column='id_proceso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.proceso'),
        ),
    ]
