# Generated by Django 5.2.7 on 2026-01-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0002_elemento_proceso_remove_planillamedicion_id_elemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTES',
            },
        ),
        migrations.RemoveField(
            model_name='planillamedicion',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='planillamedicion',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.cliente'),
        ),
    ]
