# Generated by Django 5.2.7 on 2026-01-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0003_cliente_remove_planillamedicion_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillamedicion',
            name='articulo',
            field=models.ForeignKey(blank=True, db_column='id_articulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.articulo'),
        ),
    ]
