# Generated by Django 5.2.7 on 2026-01-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0004_alter_planillamedicion_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
