# Generated by Django 5.2.7 on 2026-01-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0005_proceso_descripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valormedicion',
            unique_together={('planilla', 'control', 'pieza')},
        ),
    ]
