# Generated by Django 5.2.7 on 2026-01-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0006_alter_valormedicion_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código/Inventario')),
                ('tipo', models.CharField(choices=[('CALIBRE', 'Calibre'), ('MICROMETRO', 'Micrómetro'), ('COMPARADOR', 'Comparador'), ('GALGA', 'Galga'), ('OTRO', 'Otro')], default='CALIBRE', max_length=20)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_calibracion', models.DateField(blank=True, null=True, verbose_name='Última Calibración')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'INSTRUMENTOS',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código/Interno')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'db_table': 'MAQUINAS',
            },
        ),
        migrations.AddField(
            model_name='tolerancia',
            name='instrumento',
            field=models.ForeignKey(blank=True, db_column='fk_instrumento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='planillamedicion',
            name='maquina',
            field=models.ForeignKey(blank=True, db_column='id_maquina', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.maquina', verbose_name='Máquina'),
        ),
    ]
