# Generated by Django 5.2.7 on 2026-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='x_pos',
            field=models.FloatField(blank=True, null=True, verbose_name='Posición X (%)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='y_pos',
            field=models.FloatField(blank=True, null=True, verbose_name='Posición Y (%)'),
        ),
    ]
