# Generated by Django 5.2.11 on 2026-02-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0009_maquina_x_pos_maquina_y_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolerancia',
            name='maximo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tolerancia',
            name='minimo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tolerancia',
            name='nominal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
