# Generated by Django 5.2.11 on 2026-02-12 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0010_alter_tolerancia_maximo_alter_tolerancia_minimo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planillamedicion',
            name='aprobador',
            field=models.ForeignKey(blank=True, db_column='fk_aprobador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planillamedicion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
