# Generated by Django 5.2.11 on 2026-02-12 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0011_planillamedicion_aprobador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='alerta_dias',
            field=models.IntegerField(default=15, verbose_name='Alerta Anticipada (Días)'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='certificado_nro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. Certificado'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='en_servicio',
            field=models.BooleanField(default=True, verbose_name='En Servicio'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='frecuencia_meses',
            field=models.IntegerField(default=12, verbose_name='Frecuencia (Meses)'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='proxima_calibracion',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Calibración'),
        ),
        migrations.CreateModel(
            name='HistorialCalibracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calibracion', models.DateField()),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=20)),
                ('certificado_nro', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mediciones.instrumento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Calibración',
                'verbose_name_plural': 'Historial de Calibraciones',
                'db_table': 'INSTRUMENTO_CALIBRACIONES',
                'ordering': ['-fecha_calibracion'],
            },
        ),
    ]
