# Generated by Django 5.2.11 on 2026-02-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0012_instrumento_alerta_dias_instrumento_certificado_nro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcalibracion',
            name='archivo_certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Archivo del Certificado'),
        ),
    ]
