# Generated by Django 5.2.11 on 2026-02-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0013_historialcalibracion_archivo_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.cliente', verbose_name='Cliente Dueño (si aplica)'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='es_obsoleto',
            field=models.BooleanField(default=False, verbose_name='Obsoleto / Baja'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='es_propio',
            field=models.BooleanField(default=True, verbose_name='Propiedad de ABBAMAT'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='rango',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rango de Medición'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. de Serie'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Física'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='tipo',
            field=models.CharField(choices=[('CALIBRE', 'Calibre / Pie de Rey'), ('MICROMETRO', 'Micrómetro'), ('COMPARADOR', 'Comparador'), ('GALGA', 'Galga'), ('ALESOMETRO', 'Alesómetro'), ('PNP', 'Pasa / No Pasa (Tapón/Anillo)'), ('PATRON', 'Bloques Patrón / Standard'), ('OTRO', 'Otro / Especial')], default='CALIBRE', max_length=20),
        ),
    ]
