# Generated by Django 5.2.11 on 2026-02-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0014_instrumento_cliente_instrumento_es_obsoleto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gemini API Key'),
        ),
    ]
