# Generated by Django 5.2.11 on 2026-02-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0015_profile_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alerta_calibracion_dias',
            field=models.IntegerField(default=15, verbose_name='Días anticipación alerta'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tema_preferido',
            field=models.CharField(choices=[('LIGHT', 'Claro'), ('DARK', 'Oscuro')], default='LIGHT', max_length=10),
        ),
    ]
