# Generated by Django 5.2.11 on 2026-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0016_profile_alerta_calibracion_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gemini_model_name',
            field=models.CharField(default='gemini-2.5-flash', max_length=50, verbose_name='Modelo de IA'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tema_preferido',
            field=models.CharField(choices=[('LIGHT', 'Claro (Clásico)'), ('DARK', 'Oscuro (Luna)'), ('BENTO', 'Bento Modern Industrial'), ('GLASS', 'Frosted Aurora (Cristal)'), ('NEU', 'Neumorphic Soft Pro'), ('CYBER', 'Cyberpunk / Midnight Neon'), ('STUDIO', 'Minimalist Studio (Ink)')], default='LIGHT', max_length=20),
        ),
    ]
