# Generated by Django 5.2.11 on 2026-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0017_profile_gemini_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave del Parámetro')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Valor del Parámetro')),
            ],
            options={
                'verbose_name': 'Configuración de Sistema',
                'verbose_name_plural': 'Configuraciones de Sistema',
                'db_table': 'SYSTEM_CONFIG',
            },
        ),
    ]
