# Generated by Django 5.2.11 on 2026-08-06 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0018_systemconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operario',
                'verbose_name_plural': 'Operarios',
                'db_table': 'OPERARIOS',
            },
        ),
    ]
